version: '3.9'
services:
    rabbitmq:
        image: rabbitmq:3-management
        ports: 
            - "8080:15672"
            - "5672:5672"
        networks: 
            - backend
networks:
    backend:
        driver: bridge